apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Optional but recommended
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx          # important for newer NGINX Ingress
  rules:
  - http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80

      - path: /result
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 80

      - path: /
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 80

